eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${server.port}
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
logging:
  level:
    ROOT: debug